### PR TITLE
Fix issues and update packages

### PR DESCRIPTION
**Pull request by w3bdesign**
1. Updated all NPM packages
2. React is updated to React 17
3. Replaced jQuery in App.js with native JavaScript fetch()
4. Fix https://github.com/rammazzoti2000/personal_portfolio/issues/35 
5. Fix https://github.com/rammazzoti2000/personal_portfolio/issues/33 by replacing the GIF with a CSS based spinner (you can customize the CSS and design in siteload.css)

### CODE REVIEW

**Comment by w3bdesign** [comment]
@rammazzoti2000

**Comment by rammazzoti2000** [comment]
@w3bdesign the new spinner works very well.
As for the fix for the mobile menu, the class `current` is being assigned to the parent `li` only the first time so when I get back to home the text is not being highlighted anymore because is missing class `current`.

What I would do is just forget about this bug and revert it like it was before. I will also close the issue referenced so it doesn't create confusion.

**Comment by w3bdesign** [comment]
@rammazzoti2000 See https://github.com/rammazzoti2000/personal_portfolio/pull/39/commits/fa9178074a2a5f0aff6db3619dc0a84866b390f5

I have reverted the Header.js to how it was before.

**Review by rammazzoti2000 — APPROVED** [review]
@w3bdesign  Pull Request approved, you can merge it.
Thank you again for your interest and contribution on the project.

**Comment by w3bdesign** [comment]
@rammazzoti2000 I do not have write access, so you need to merge this pull request.

**Comment by rammazzoti2000** [comment]
@w3bdesign I thought by approving it will let you merge it.

**Pull request merged**
